# Generated by Django 5.1.5 on 2025-01-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название рецепта')),
                ('ingredients', models.CharField(max_length=400, verbose_name='Ингредиенты')),
                ('instructions', models.TextField(verbose_name='Инструкция по приготовлению')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(blank=True, choices=[('Завтрак', 'Завтрак'), ('Основное блюдо', 'Основное блюдо'), ('Салат', 'Салат'), ('Суп', 'Суп'), ('Десерт', 'Десерт'), ('Закуска', 'Закуска')], default='Основное блюдо', max_length=50, null=True, verbose_name='Категория')),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Легко'), ('Medium', 'Средне'), ('Hard', 'Сложно')], max_length=10, null=True, verbose_name='Сложность приготовления')),
                ('prep_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время приготовления (минуты)')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
